backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles:
    - admin
    - editor
    - Admin
    - Editor

publish_mode: editorial_workflow
site_url: https://louiswhite.me
display_url: https://louiswhite.me

media_folder: static/img
public_folder: img

collections:
  - name: 'blog-posts'
    label: 'Blog Posts'
    preview_path: '/{{slug}}'
    folder: 'static/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about.md'
        label: 'About'
        name: 'about'
        preview_path: '/about'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
          - { label: Title, name: title, widget: string }