backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles:
    - admin
    - editor
    - Admin
    - Editor

publish_mode: editorial_workflow
site_url: 
display_url: 

media_folder: static/img
public_folder: img