name: Push to public

on: 
    push:
      branches:
       - master

jobs:
  repo-sync:

    runs-on: ubuntu-latest

    steps:
    - name: repo-sync
      uses: wei/git-sync@master
      env: 
        SOURCE_REPO: "https://omawhite:${{secrets.GH_ACCESS_TOKEN}}@github.com/omawhite/portfolio.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "https://omawhite:${{secrets.GH_ACCESS_TOKEN}}@github.com/omawhite/louiswhite.me.git"
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH